[09:55:36] [User Authenticator #1/ERROR] [luckperms]: Exception occurred whilst loading data for 88756d01-aff5-40b2-a394-db6592366574 - Optional[Bilbbo_Bagins]
[09:55:36] [User Authenticator #1/INFO] [STDERR]: [me.lucko.luckperms.sponge.listeners.SpongeConnectionListener:onClientAuth:86]: java.util.concurrent.CompletionException: org.h2.jdbc.JdbcSQLNonTransientConnectionException: Database may be already in use: null. Possible solutions: close all other connection(s); use the server mode [90020-198]
[09:55:36] [User Authenticator #1/INFO] [STDERR]: [me.lucko.luckperms.sponge.listeners.SpongeConnectionListener:onClientAuth:86]:       at me.lucko.luckperms.common.storage.Storage.lambda$makeFuture$0(Storage.java:86)
[09:55:36] [User Authenticator #1/INFO] [STDERR]: [me.lucko.luckperms.sponge.listeners.SpongeConnectionListener:onClientAuth:86]:       at java.util.concurrent.CompletableFuture$AsyncSupply.run(Unknown Source)
[09:55:36] [User Authenticator #1/INFO] [STDERR]: [me.lucko.luckperms.sponge.listeners.SpongeConnectionListener:onClientAuth:86]:       at org.spongepowered.api.scheduler.Task$Builder.lambda$execute$0(Task.java:139)
[09:55:36] [User Authenticator #1/INFO] [STDERR]: [me.lucko.luckperms.sponge.listeners.SpongeConnectionListener:onClientAuth:86]:       at org.spongepowered.common.scheduler.SchedulerBase.lambda$startTask$0(SchedulerBase.java:197)
[09:55:36] [User Authenticator #1/INFO] [STDERR]: [me.lucko.luckperms.sponge.listeners.SpongeConnectionListener:onClientAuth:86]:       at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
[09:55:36] [User Authenticator #1/INFO] [STDERR]: [me.lucko.luckperms.sponge.listeners.SpongeConnectionListener:onClientAuth:86]:       at java.util.concurrent.FutureTask.run(Unknown Source)
[09:55:36] [User Authenticator #1/INFO] [STDERR]: [me.lucko.luckperms.sponge.listeners.SpongeConnectionListener:onClientAuth:86]:       at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
[09:55:36] [User Authenticator #1/INFO] [STDERR]: [me.lucko.luckperms.sponge.listeners.SpongeConnectionListener:onClientAuth:86]:       at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
[09:55:36] [User Authenticator #1/INFO] [STDERR]: [me.lucko.luckperms.sponge.listeners.SpongeConnectionListener:onClientAuth:86]:       at java.lang.Thread.run(Unknown Source)
[09:55:36] [User Authenticator #1/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:-1]: Caused by: org.h2.jdbc.JdbcSQLNonTransientConnectionException: Database may be already in use: null. Possible solutions: close all other connection(s); use the server mode [90020-198]
[09:55:36] [User Authenticator #1/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:-1]:     at org.h2.message.DbException.getJdbcSQLException(DbException.java:616)
[09:55:36] [User Authenticator #1/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:-1]:     at org.h2.message.DbException.getJdbcSQLException(DbException.java:427)
[09:55:36] [User Authenticator #1/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:-1]:     at org.h2.message.DbException.get(DbException.java:194)
[09:55:36] [User Authenticator #1/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:-1]:     at org.h2.mvstore.db.MVTableEngine$Store.convertIllegalStateException(MVTableEngine.java:193)
[09:55:36] [User Authenticator #1/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:-1]:     at org.h2.mvstore.db.MVTableEngine$Store.open(MVTableEngine.java:173)
[09:55:36] [User Authenticator #1/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:-1]:     at org.h2.mvstore.db.MVTableEngine.init(MVTableEngine.java:95)
[09:55:36] [User Authenticator #1/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:-1]:     at org.h2.engine.Database.getPageStore(Database.java:2740)
[09:55:36] [User Authenticator #1/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:-1]:     at org.h2.engine.Database.open(Database.java:769)
[09:55:36] [User Authenticator #1/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:-1]:     at org.h2.engine.Database.openDatabase(Database.java:319)
[09:55:36] [User Authenticator #1/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:-1]:     at org.h2.engine.Database.<init>(Database.java:313)
[09:55:36] [User Authenticator #1/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:-1]:     at org.h2.engine.Engine.openSession(Engine.java:69)
[09:55:36] [User Authenticator #1/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:-1]:     at org.h2.engine.Engine.openSession(Engine.java:201)
[09:55:36] [User Authenticator #1/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:-1]:     at org.h2.engine.Engine.createSessionAndValidate(Engine.java:178)
[09:55:36] [User Authenticator #1/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:-1]:     at org.h2.engine.Engine.createSession(Engine.java:161)
[09:55:36] [User Authenticator #1/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:-1]:     at org.h2.engine.Engine.createSession(Engine.java:31)
[09:55:36] [User Authenticator #1/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:-1]:     at org.h2.engine.SessionRemote.connectEmbeddedOrServer(SessionRemote.java:336)
[09:55:36] [User Authenticator #1/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:-1]:     at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:124)
[09:55:36] [User Authenticator #1/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:-1]:     at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:103)
[09:55:36] [User Authenticator #1/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:-1]:     at org.h2.Driver.connect(Driver.java:69)
[09:55:36] [User Authenticator #1/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:-1]:     at me.lucko.luckperms.common.storage.implementation.sql.connection.file.H2ConnectionFactory.getConnection(H2ConnectionFactory.java:83)
[09:55:36] [User Authenticator #1/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:-1]:     at me.lucko.luckperms.common.storage.implementation.sql.SqlStorage.getPlayerName(SqlStorage.java:1017)
[09:55:36] [User Authenticator #1/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:-1]:     at me.lucko.luckperms.common.storage.implementation.sql.SqlStorage.savePlayerData(SqlStorage.java:947)
[09:55:36] [User Authenticator #1/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:-1]:     at me.lucko.luckperms.common.storage.Storage.lambda$savePlayerData$20(Storage.java:254)
[09:55:36] [User Authenticator #1/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:-1]:     at me.lucko.luckperms.common.storage.Storage.lambda$makeFuture$0(Storage.java:81)
[09:55:36] [User Authenticator #1/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:-1]:     ... 8 more
[09:55:36] [User Authenticator #1/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:-1]: Caused by: java.lang.IllegalStateException: The file is locked: nio:C:/Users/Alex/AppData/Roaming/.minecraft/luckperms/luckperms-h2.mv.db [1.4.198/7]
[09:55:36] [User Authenticator #1/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:-1]:     at org.h2.mvstore.DataUtils.newIllegalStateException(DataUtils.java:883)
[09:55:36] [User Authenticator #1/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:-1]:     at org.h2.mvstore.FileStore.open(FileStore.java:172)
[09:55:36] [User Authenticator #1/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:-1]:     at org.h2.mvstore.MVStore.<init>(MVStore.java:390)
[09:55:36] [User Authenticator #1/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:-1]:     at org.h2.mvstore.MVStore$Builder.open(MVStore.java:3343)
[09:55:36] [User Authenticator #1/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:-1]:     at org.h2.mvstore.db.MVTableEngine$Store.open(MVTableEngine.java:162)
[09:55:36] [User Authenticator #1/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:-1]:     ... 27 more
[09:55:36] [User Authenticator #1/ERROR] [luckperms]: Player connection was re-allowed for 88756d01-aff5-40b2-a394-db6592366574
[09:55:36] [User Authenticator #1/INFO] [minecraft/NetHandlerLoginServer]: Disconnecting com.mojang.authlib.GameProfile@2dab8ade[id=88756d01-aff5-40b2-a394-db6592366574,name=Bilbbo_Bagins,properties={textures=[Property{name=textures, value=eyJ0aW1lc3RhbXAiOjE1NzM0ODQxMzMzNDQsInByb2ZpbGVJZCI6Ijg4NzU2ZDAxYWZmNTQwYjJhMzk0ZGI2NTkyMzY2NTc0IiwicHJvZmlsZU5hbWUiOiJCaWxiYm9fQmFnaW5zIiwidGV4dHVyZXMiOnsiU0tJTiI6eyJ1cmwiOiJodHRwOi8vdGV4dHVyZXMubWluZWNyYWZ0Lm5ldC90ZXh0dXJlLzVjYzRjZTExMTMzZGM1YzJlMDYyYjIyNTZmOTY1MDYwMDU2ODVhNjBlYjNhMTJhMGNhMjY3M2M3MWQ0YjBkNWQifX19, signature=FiRd934NLPu7O/8X2n1qWB/nevNrIhlpBTIxsPVhdexIAvRdLyIJGOwGqVPrUjlX2z7XDtBDlZil+cBeC/BmH3aokvAirEZX7oDdXjo6tUDBZkScAK2feSWm6fmdCVrPN3RBOqhjm/PW5jrkFSvSEy3DAB8kwvXcdYGzNqq/ukzGdQf5YIzoAHAD3+0VC5PIa8O/nPgEEv8xavaGc/yslbSJsRu83x3KCQBXIjNq3I2mcAEiiG4co5kPg/FnnCMw/K03deewJEn+StcY1zzQXtSf+pXivFe7rgK3BeaU9mXsEDrMTBNLuU+JU341uFdvFg8C4hSolypcgy4YeKFAbddeBXlXCGkbpXu4bWGPdOrHx9heCDxU8ttKvhy0CbC8LXhF4hru75JJgoiHeGOpZ+0lGstv7kc+ND685Ro9e79D+PhmPb+qpmxpYcQ0oscceEBnCBxNMtXNZzDnC+EKM4jGsWKiEgejEc9NHM6H8FRGOYVjkCOlHSksc++L3Icetb+ipozomwiUne8JgJhFqU7xS6ccEZVtWEcy4n9QdyrCouN1MbgSZ1RwiT9m9d0IsII2DXP1I9GnU7T2lq7k89qqA+7MKlI8yZLfeodoPPXj6MTCgv2rhrrh8CJ5UoUN38toMlyreByykNF44fyvTiQfnQoaPdQuGxfsMpWdbvE=}]},legacy=false] (/192.168.2.241:59484): [LP] A database error occurred whilst loading permissions data. Please try again later. If you are a server admin, please check the console for any errors.
[09:55:36] [Server thread/INFO] [minecraft/NetHandlerLoginServer]: com.mojang.authlib.GameProfile@2dab8ade[id=88756d01-aff5-40b2-a394-db6592366574,name=Bilbbo_Bagins,properties={textures=[Property{name=textures, value=eyJ0aW1lc3RhbXAiOjE1NzM0ODQxMzMzNDQsInByb2ZpbGVJZCI6Ijg4NzU2ZDAxYWZmNTQwYjJhMzk0ZGI2NTkyMzY2NTc0IiwicHJvZmlsZU5hbWUiOiJCaWxiYm9fQmFnaW5zIiwidGV4dHVyZXMiOnsiU0tJTiI6eyJ1cmwiOiJodHRwOi8vdGV4dHVyZXMubWluZWNyYWZ0Lm5ldC90ZXh0dXJlLzVjYzRjZTExMTMzZGM1YzJlMDYyYjIyNTZmOTY1MDYwMDU2ODVhNjBlYjNhMTJhMGNhMjY3M2M3MWQ0YjBkNWQifX19, signature=FiRd934NLPu7O/8X2n1qWB/nevNrIhlpBTIxsPVhdexIAvRdLyIJGOwGqVPrUjlX2z7XDtBDlZil+cBeC/BmH3aokvAirEZX7oDdXjo6tUDBZkScAK2feSWm6fmdCVrPN3RBOqhjm/PW5jrkFSvSEy3DAB8kwvXcdYGzNqq/ukzGdQf5YIzoAHAD3+0VC5PIa8O/nPgEEv8xavaGc/yslbSJsRu83x3KCQBXIjNq3I2mcAEiiG4co5kPg/FnnCMw/K03deewJEn+StcY1zzQXtSf+pXivFe7rgK3BeaU9mXsEDrMTBNLuU+JU341uFdvFg8C4hSolypcgy4YeKFAbddeBXlXCGkbpXu4bWGPdOrHx9heCDxU8ttKvhy0CbC8LXhF4hru75JJgoiHeGOpZ+0lGstv7kc+ND685Ro9e79D+PhmPb+qpmxpYcQ0oscceEBnCBxNMtXNZzDnC+EKM4jGsWKiEgejEc9NHM6H8FRGOYVjkCOlHSksc++L3Icetb+ipozomwiUne8JgJhFqU7xS6ccEZVtWEcy4n9QdyrCouN1MbgSZ1RwiT9m9d0IsII2DXP1I9GnU7T2lq7k89qqA+7MKlI8yZLfeodoPPXj6MTCgv2rhrrh8CJ5UoUN38toMlyreByykNF44fyvTiQfnQoaPdQuGxfsMpWdbvE=}]},legacy=false] (/192.168.2.241:59484) lost connection: [LP] A database error occurred whilst loading permissions data. Please try again later. If you are a server admin, please check the console for any errors.
